# These are supported funding model platforms

github: BeanGreen247
patreon: BeanGreen247
#open_collective: # Replace with a single Open Collective username
ko_fi: beangreen247
buy_me_a_coffee: beangreen247
